abstract class StringsManager {
  static const appName = "UpTodo";
  static const onboarding1 = "Manage your tasks";
  static const onboarding1Description =
      "You can easily manage all of your daily \n tasks in UpTodo for free";
  static const onboarding2 = "Create daily routine";
  static const onboarding2Description =
      "In Uptodo  you can create your\n personalized routine to stay productive";
  static const onboarding3 = "Orgonaize your tasks";
  static const onboarding3Description =
      "You can organize your daily tasks by\n adding your tasks into separate categories";
  static const skip = 'SKIP';
  static const next = 'NEXT';
  static const back = 'BACK';
  static const getStarted = 'GETSTARTED';
  static const login = 'Login';
  static const register = 'Register';
  static const username = 'Username';
  static const enterUsername = 'Enter your Username';
  static const password = 'Password';
  static const confirmPassword = 'Confirm Password';
  static const enterPassword = '••••••••••••••';
  static const loginWithGoogle = 'Login with Google';
  static const loginWithFacebook = 'Login with Facebook';
  static const dontHaveAccount = 'Don’t have an account? ';
  static const alreadyHaveAccount = 'Already have an account? ';
  static const index = 'Index';
  static const calendar = 'Calendar';
  static const focus = 'Focus';
  static const profile = 'Profile';
  static const addTask = 'Add Task';
  static const taskTitle = 'Task Title';
  static const taskDescription = 'Task Description';
  static const chooseTime = 'Choose Time';
  static const taskPriority = 'Task Priority';
  static const cancel = 'Cancel';
  static const save = 'Save';
  static const chooseCategory = 'Choose Category';
  static const createNew = 'Create New Category';
  static const categoryName = 'Category Name';
  static const categoryIcon = 'Category Icon';
  static const categoryColor = 'Category Color';
  static const chooseIcon = 'Choose Icon';
  static const chooseColor = 'Choose Color';
  static const pickAColor = 'Pick a color';
  static const name = 'Name';
  static const priority = 'Priority';
  static const search = 'Search for your task...';
  static const today = 'Today';
  static const tomorrow = 'Tomorrow';
  static const yesterday = 'Yesterday';
  static const completed = 'Completed';
  static const editTitleAndDescription = 'Edit Title and Description';
  static const taskTime = 'Task Time';
  static const taskCategory = 'Task Category';
  static const deleteTask = 'Delete Task';
  static const finished = 'Finished';
  static const missed = 'Missed';
}
